#!/bin/bash

# This file calculates some data backups.
# Backing up the live database does not give a consistent backup

HAHOME=/home/homeassistant
MAXSIZE=$((1024 * 1024 * 1024)) # = 1GB

export BACKUPDIR="$HAHOME/var/BACKUP"

function postgres_bu () {
    DATABASE=$1
    BACKUP=$2

    pg_dump -Fc $DATABASE > $BACKUP
}

function sqlite_bu () {
    DATABASE=$1
    BACKUP=$2
    
    size=`stat -c '%s' $DATABASE`
    if [[ $size -gt $MAXSIZE ]]; then
        CLONE="$DATABASE-clone"
        sqlite3 $DATABASE ".clone $CLONE"
        DATABASE=$CLONE
    fi

    sqlite3 $DATABASE "VACUUM INTO '$BACKUP';"
    
    if [ -f $CLONE ]; then
        rm -f $CLONE
    fi

    gzip -f $BACKUP
}

mkdir -p $BACKUPDIR

HA_DB=hadb
HA_DB_BACKUP=$BACKUPDIR/hadb.backup
postgres_bu $HA_DB $HA_DB_BACKUP

DECONZ_DB=/home/pi/.local/share/dresden-elektronik/deCONZ/zll.db
DECONZ_DB_BACKUP=$BACKUPDIR/zll.db.backup
sqlite_bu $DECONZ_DB $DECONZ_DB_BACKUP
